config/routes.rb
Puzzle::Application.routes.draw do
  resources :users

  resources :solvings

  resources :crosswords

   match 'login', :to => 'user_sessions#new'
   match 'logout', :to => 'user_sessions#destroy'

   resources :users, :solvings, :crosswords
   resources :user_sessions, :only => :create

   root :to => "users#index"

end

app/models/crossword.rb
require 'utility_helper'

class Crossword < ActiveRecord::Base  
  belongs_to :author, :class_name => "User"
 
  has_attached_file :picture, :path => ":rails_root/public/system/:attachment/:id/:style/:server_file_name",
                              :url => "/system/:attachment/:id/:style/:server_file_name"
  validates_attachment_size :picture, :less_than => 1.megabyte, :message => "size should be less then 1Mb" 
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png', 'image/gif'], 
                                    :message => "file should be of supported type (jpeg, png, gif)"  
  
  Paperclip.interpolates :server_file_name do |attachment, style|
    attachment.instance.server_file_name
  end
  
  after_save :set_puzzle_data
  
  serialize :data
  
  def server_file_name
    self.picture_file_name.gsub(/\s+/, '_') 
  end
  
  private
  def set_puzzle_data
    return unless self.data.blank?
    
    image = MiniMagick::Image.open self.picture.path
    width, height = image["dimensions"]
    
    self.block_height = self.block_width*height/width if (5..50).include? self.block_width
    self.block_height, self.block_width = set_proportional_measures *[width, height].sort unless (5..50).include? self.block_height
    self.block_height, self.block_width = self.block_width, self.block_height if width > height
        
    data = get_image_data image, block_width, block_height
    self.update_attributes :data => data, :block_width => self.block_width, :block_height => self.block_height
    MiniMagick::Image.new(self.picture.path).resize "#{self.block_width*5}x#{self.block_height*5}"
  end
  
  def set_proportional_measures small_side, large_side 
    large = (5..50).edge_value(large_side > 150 ? large_side/5 : 30)
    small = (5..50).edge_value(large * small_side / large_side)
    return large, small
  end
  
  def get_image_data image, width, height
    image.combine_options do |c|
      c.resize "#{width}x#{height}"
      c << '+dither'
      c.colorspace "gray"
      c.colors 2
      c.normalize
    end
    (image.run_command "convert", image.escaped_path, "txt:-").split("\n")[1..-1].inject([[]]) do |res, elem|
      val = elem =~ /#0/ ? 1 : 0
      res.last.length < width ? res.last.push(val) : res.push([val])
      res
    end
  end

end

app/models/solving.rb
class Solving < ActiveRecord::Base
  belongs_to :user
  belongs_to :puzzle
  
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic {|c| c.require_password_confirmation = false}
  
  has_many :puzzles
  has_many :solvings
  
  def full_name
    name || email
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  include ActiveModel::Conversion 
  
  def persisted? 
    false 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user_session, :current_user 

  protected
  def current_user_session 
    @current_user_session || (@current_user_session = UserSession.find) || UserSession.new  
  end
  
  def current_user 
    @current_user || @current_user = (current_user_session && current_user_session.user) 
  end
end

app/controllers/crosswords_controller.rb
class CrosswordsController < ApplicationController
  before_filter :find_crossword, :except => [:new, :create]
  
  def new
    @crossword = Crossword.new
  end

  def create
   @crossword = Crossword.new params[:crossword]
   if @crossword.save
     redirect_to(edit_crossword_path @crossword)
   else
     render :action => :new
   end
  end
  
  protected
  def find_crossword
    @crossword = Crossword.find_by_id params[:id]
  end
  
end

app/controllers/solvings_controller.rb
class SolvingsController < ApplicationController
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new params[:user_session]
    if @user_session.save
      redirect_to root_url
    else
      render :action => :new
    end
  end
  
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, :only => [:edit, :update, :show, :destroy]
  before_filter :validate_current_user, :only => [:edit, :update, :destroy]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new params[:user]
    if @user.save
      flash[:notice] = "Successfully created user."
      redirect_to @user
    else
      render :action => 'new'
    end
  end
  
  def update
    if @user.update_attributes params[:user]
      redirect_to @user
    else
      render :action => :edit
    end 
  end
  
  private
  def validate_current_user
    @user == current_user
  end
  
  def find_user
    @user = User.find_by_id params[:id]
    redirect_to users_path if @user.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/crosswords/edit.haml
#edit.puzzle_area
  =image_tag @crossword.picture.url
  %table
    -@crossword.data.each_with_index do |row_data, row|
      %tr
        -row_data.each_with_index do |item, col|
          %td{ :id => "#{row}_#{col}", :class => item.zero? ? "" : "checked"}

app/views/crosswords/new.haml
=semantic_form_for @crossword, :html => {:multipart => true} do |f|
  =f.inputs do
    =f.input :picture, :as => :file
    =f.input :block_width, :label => "Puzzle width", :required => false
    Puzzle height will be set proportionally
    
  =f.buttons do
    =f.commit_button    
    

app/views/crosswords/show.haml
=image_tag @crossword.picture.url 
=@crossword.inspect

Block_height:
=@crossword.block_height
Block_width:
=@crossword.block_width


Img data:
=@crossword.data.inspect

app/views/layouts/application.haml
!!! Strict
%html
  %head
    %title Puzzles #{"| " + current_user.full_name if current_user }
    = stylesheet_link_tag 'style', 'formtastic', 'puzzles'
    = javascript_include_tag 'jquery-1.4.1.min', 'puzzles'
  %body
    #container
      #curr_user
        Current user:
        %b= current_user.try(:email) || "none"
        -if current_user
          |
          = link_to 'Log out', logout_path
          |
          = link_to 'Edit', edit_user_path(current_user)
        -else
          |
          =link_to 'Log in', login_path
      %hr
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      
      = yield

app/views/user_sessions/new.haml
=semantic_form_for UserSession.new do |form|
  =form.inputs do
    =form.input :email
    =form.input :password
  =form.buttons do
    =form.commit_button "LogIn"

app/views/users/_user.haml
%p
  %strong Name:
  =user.name
%p
  %strong Email:
  =user.email
  
- if user == current_user
  = link_to "Edit", edit_user_path(user)
  |
  = link_to "Delete", {:action => "destroy", :id => current_user}, :confirm => "Are you sure?", :method => :delete

app/views/users/edit.haml
=semantic_form_for @user do |user_form|
  =user_form.inputs :name
  =user_form.buttons do
    =user_form.commit_button
%p
  = link_to "View All", users_path

app/views/users/index.haml
= render :partial => "user", :collection => @users
%p= link_to "New User", new_user_path

app/views/users/new.haml
-semantic_form_for @user do |f|
  -f.inputs :name, :email, :password, :password_confirmation
  -f.buttons do
    =f.commit_button
    
%p=link_to "Back to List", users_path

app/views/users/show.haml
=render :partial => "user", :object => @user
%p= link_to "View All", users_path